
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('foods').del()
    .then(function () {
      // Inserts seed entries
      return knex('foods').insert([
        {id: 1, name: "açaí", type: "fruit"},
        {id: 2, name: "apple", type: "fruit"},
        {id: 3, name: "akee", type: "fruit"},
        {id: 4, name: "apricot", type: "fruit"},
        {id: 5, name: "avocado", type: "fruit"},
        {id: 6, name: "banana", type: "fruit"},
        {id: 7, name: "bilberry", type: "fruit"},
        {id: 8, name: "blackberry", type: "fruit"},
        {id: 9, name: "blackcurrant", type: "fruit"},
        {id: 10, name: "black", type: "fruit"},
        {id: 11, name: "sapote", type: "fruit"},
        {id: 12, name: "blueberry", type: "fruit"},
        {id: 13, name: "boysenberry", type: "fruit"},
        {id: 14, name: "crab apples", type: "fruit"},
        {id: 15, name: "currant", type: "fruit"},
        {id: 16, name: "cherry", type: "fruit"},
        {id: 17, name: "cherimoya", type: "fruit"},
        {id: 18, name: "chico fruit", type: "fruit"},
        {id: 19, name: "cloudberry", type: "fruit"},
        {id: 20, name: "coconut", type: "fruit"},
        {id: 21, name: "cranberry", type: "fruit"},
        {id: 22, name: "cucumber", type: "fruit"},
        {id: 23, name: "custard apple", type: "fruit"},
        {id: 24, name: "damson", type: "fruit"},
        {id: 25, name: "date", type: "fruit"},
        {id: 26, name: "dragonfruit", type: "fruit"},
        {id: 27, name: "durian", type: "fruit"},
        {id: 28, name: "elderberry", type: "fruit"},
        {id: 29, name: "feijoa", type: "fruit"},
        {id: 30, name: "fig", type: "fruit"},
        {id: 31, name: "goji berry", type: "fruit"},
        {id: 32, name: "gooseberry", type: "fruit"},
        {id: 33, name: "grape", type: "fruit"},
        {id: 34, name: "raisin", type: "fruit"},
        {id: 35, name: "grapefruit", type: "fruit"},
        {id: 36, name: "guava", type: "fruit"},
        {id: 37, name: "honeyberry", type: "fruit"},
        {id: 38, name: "huckleberry", type: "fruit"},
        {id: 39, name: "jabuticaba", type: "fruit"},
        {id: 40, name: "jackfruit", type: "fruit"},
        {id: 41, name: "jambul", type: "fruit"},
        {id: 42, name: "japanese plum", type: "fruit"},
        {id: 43, name: "jostaberry", type: "fruit"},
        {id: 44, name: "jujube", type: "fruit"},
        {id: 45, name: "juniper berry", type: "fruit"},
        {id: 46, name: "kiwano", type: "fruit"},
        {id: 47, name: "kiwifruit", type: "fruit"},
        {id: 48, name: "kumquat", type: "fruit"},
        {id: 49, name: "lemon", type: "fruit"},
        {id: 50, name: "lime", type: "fruit"},
        {id: 51, name: "loquat", type: "fruit"},
        {id: 52, name: "longan", type: "fruit"},
        {id: 53, name: "lychee", type: "fruit"},
        {id: 54, name: "mango", type: "fruit"},
        {id: 55, name: "mangosteen", type: "fruit"},
        {id: 56, name: "marionberry", type: "fruit"},
        {id: 57, name: "melon", type: "fruit"},
        {id: 58, name: "cantaloupe", type: "fruit"},
        {id: 59, name: "honeydew", type: "fruit"},
        {id: 60, name: "watermelon", type: "fruit"},
        {id: 61, name: "miraclefruit", type: "fruit"},
        {id: 62, name: "mulberry", type: "fruit"},
        {id: 63, name: "nectarine", type: "fruit"},
        {id: 64, name: "nance", type: "fruit"},
        {id: 65, name: "olive", type: "fruit"},
        {id: 66, name: "orange", type: "fruit"},
        {id: 67, name: "blood orange", type: "fruit"},
        {id: 68, name: "clementine", type: "fruit"},
        {id: 69, name: "mandarine", type: "fruit"},
        {id: 70, name: "tangerine", type: "fruit"},
        {id: 71, name: "papaya", type: "fruit"},
        {id: 72, name: "passionfruit", type: "fruit"},
        {id: 73, name: "peach", type: "fruit"},
        {id: 74, name: "pear", type: "fruit"},
        {id: 75, name: "persimmon", type: "fruit"},
        {id: 76, name: "plantain", type: "fruit"},
        {id: 77, name: "plum", type: "fruit"},
        {id: 78, name: "prune", type: "fruit"},
        {id: 79, name: "pineapple", type: "fruit"},
        {id: 80, name: "pineberry", type: "fruit"},
        {id: 81, name: "plumcot", type: "fruit"},
        {id: 82, name: "pomegranate", type: "fruit"},
        {id: 83, name: "pomelo", type: "fruit"},
        {id: 84, name: "purple mangosteen", type: "fruit"},
        {id: 85, name: "quince", type: "fruit"},
        {id: 86, name: "raspberry", type: "fruit"},
        {id: 87, name: "salmonberry", type: "fruit"},
        {id: 88, name: "rambutan", type: "fruit"},
        {id: 89, name: "redcurrant", type: "fruit"},
        {id: 90, name: "salal berry", type: "fruit"},
        {id: 91, name: "salak", type: "fruit"},
        {id: 92, name: "satsuma", type: "fruit"},
        {id: 93, name: "soursop", type: "fruit"},
        {id: 94, name: "star apple", type: "fruit"},
        {id: 95, name: "star fruit", type: "fruit"},
        {id: 96, name: "strawberry", type: "fruit"},
        {id: 97, name: "surinam cherry", type: "fruit"},
        {id: 98, name: "tamarillo", type: "fruit"},
        {id: 99, name: "tamarind", type: "fruit"},
        {id: 100, name: "ugli fruit", type: "fruit"},
        {id: 101, name: "yuzu", type: "fruit"},
        {id: 102, name: "white currant", type: "fruit"},
        {id: 103, name: "white sapote", type: "fruit"},
        {id: 104, name: "aubergine ", type: "vegetable"},
        {id: 105, name: "amrud", type: "vegetable"},
        {id: 106, name: "asparagus", type: "vegetable"},
        {id: 107, name: "legumes", type: "vegetable"},
        {id: 108, name: "alfalfa sprouts", type: "vegetable"},
        {id: 109, name: "azuki beans ", type: "vegetable"},
        {id: 110, name: "bean sprouts", type: "vegetable"},
        {id: 111, name: "black beans", type: "vegetable"},
        {id: 112, name: "black-eyed peas", type: "vegetable"},
        {id: 113, name: "borlotti bean", type: "vegetable"},
        {id: 114, name: "broad beans", type: "vegetable"},
        {id: 115, name: "chickpeas", type: "vegetable"},
        {id: 116, name: "garbanzos", type: "vegetable"},
        {id: 117, name: "or ceci beans", type: "vegetable"},
        {id: 118, name: "green beans", type: "vegetable"},
        {id: 119, name: "kidney beans", type: "vegetable"},
        {id: 120, name: "lentils", type: "vegetable"},
        {id: 121, name: "lima beans or butter bean", type: "vegetable"},
        {id: 122, name: "mung beans", type: "vegetable"},
        {id: 123, name: "navy beans", type: "vegetable"},
        {id: 124, name: "pinto beans", type: "vegetable"},
        {id: 125, name: "runner beans", type: "vegetable"},
        {id: 126, name: "split peas", type: "vegetable"},
        {id: 127, name: "soy beans", type: "vegetable"},
        {id: 128, name: "peas", type: "vegetable"},
        {id: 129, name: "snap peas", type: "vegetable"},
        {id: 130, name: "broccoflower ", type: "vegetable"},
        {id: 131, name: "broccoli ", type: "vegetable"},
        {id: 132, name: "brussels sprouts", type: "vegetable"},
        {id: 133, name: "cabbage", type: "vegetable"},
        {id: 134, name: "kohlrabi", type: "vegetable"},
        {id: 135, name: "cauliflower", type: "vegetable"},
        {id: 136, name: "celery", type: "vegetable"},
        {id: 137, name: "endive", type: "vegetable"},
        {id: 138, name: "fiddleheads", type: "vegetable"},
        {id: 139, name: "frisee", type: "vegetable"},
        {id: 140, name: "fennel", type: "vegetable"},
        {id: 141, name: "greens", type: "vegetable"},
        {id: 142, name: "beet greens ", type: "vegetable"},
        {id: 143, name: "bok choy", type: "vegetable"},
        {id: 144, name: "chard ", type: "vegetable"},
        {id: 145, name: "collard greens", type: "vegetable"},
        {id: 146, name: "kale", type: "vegetable"},
        {id: 147, name: "mustard greens", type: "vegetable"},
        {id: 148, name: "spinach", type: "vegetable"},
        {id: 149, name: "quinoa", type: "vegetable"},
        {id: 150, name: "anise", type: "vegetable"},
        {id: 151, name: "basil", type: "vegetable"},
        {id: 152, name: "caraway", type: "vegetable"},
        {id: 153, name: "cilantro", type: "vegetable"},
        {id: 154, name: "coriander", type: "vegetable"},
        {id: 155, name: "chamomile", type: "vegetable"},
        {id: 156, name: "dill", type: "vegetable"},
        {id: 157, name: "fennel", type: "vegetable"},
        {id: 158, name: "lavender", type: "vegetable"},
        {id: 159, name: "lemon grass", type: "vegetable"},
        {id: 160, name: "marjoram", type: "vegetable"},
        {id: 161, name: "oregano", type: "vegetable"},
        {id: 162, name: "parsley", type: "vegetable"},
        {id: 163, name: "rosemary", type: "vegetable"},
        {id: 164, name: "sage", type: "vegetable"},
        {id: 165, name: "thyme", type: "vegetable"},
        {id: 166, name: "lettuce", type: "vegetable"},
        {id: 167, name: "arugula", type: "vegetable"},
        {id: 168, name: "mushrooms ", type: "vegetable"},
        {id: 169, name: "nettles", type: "vegetable"},
        {id: 170, name: "new zealand spinach", type: "vegetable"},
        {id: 171, name: "okra", type: "vegetable"},
        {id: 172, name: "onions", type: "vegetable"},
        {id: 173, name: "chives", type: "vegetable"},
        {id: 174, name: "garlic", type: "vegetable"},
        {id: 175, name: "leek", type: "vegetable"},
        {id: 176, name: "onion", type: "vegetable"},
        {id: 177, name: "shallot", type: "vegetable"},
        {id: 178, name: "scallion", type: "vegetable"},
        {id: 179, name: "artichoke", type: "vegetable"},
        {id: 180, name: "green onion ", type: "vegetable"},
        {id: 181, name: "parsley", type: "vegetable"},
        {id: 182, name: "peppers ", type: "vegetable"},
        {id: 183, name: "bell pepper", type: "vegetable"},
        {id: 184, name: "chili pepper", type: "vegetable"},
        {id: 185, name: "jalapeño", type: "vegetable"},
        {id: 186, name: "habanero", type: "vegetable"},
        {id: 187, name: "paprika", type: "vegetable"},
        {id: 188, name: "tabasco pepper", type: "vegetable"},
        {id: 189, name: "cayenne pepper", type: "vegetable"},
        {id: 190, name: "radicchio", type: "vegetable"},
        {id: 191, name: "rhubarb", type: "vegetable"},
        {id: 192, name: "root vegetables", type: "vegetable"},
        {id: 193, name: "beetroot ", type: "vegetable"},
        {id: 194, name: "mangel-wurzel", type: "vegetable"},
        {id: 195, name: "carrot", type: "vegetable"},
        {id: 196, name: "celeriac", type: "vegetable"},
        {id: 197, name: "daikon", type: "vegetable"},
        {id: 198, name: "ginger", type: "vegetable"},
        {id: 199, name: "parsnip", type: "vegetable"},
        {id: 200, name: "rutabaga", type: "vegetable"},
        {id: 201, name: "turnip", type: "vegetable"},
        {id: 202, name: "radish", type: "vegetable"},
        {id: 203, name: "wasabi", type: "vegetable"},
        {id: 204, name: "horseradish", type: "vegetable"},
        {id: 205, name: "white radish", type: "vegetable"},
        {id: 206, name: "salsify ", type: "vegetable"},
        {id: 207, name: "skirret", type: "vegetable"},
        {id: 208, name: "sweetcorn ", type: "vegetable"},
        {id: 209, name: "topinambur", type: "vegetable"},
        {id: 210, name: "squashes ", type: "vegetable"},
        {id: 211, name: "acorn squash", type: "vegetable"},
        {id: 212, name: "bitter melon", type: "vegetable"},
        {id: 213, name: "butternut squash", type: "vegetable"},
        {id: 214, name: "banana squash", type: "vegetable"},
        {id: 215, name: "zucchini ", type: "vegetable"},
        {id: 216, name: "cucumber ", type: "vegetable"},
        {id: 217, name: "delicata", type: "vegetable"},
        {id: 218, name: "gem squash", type: "vegetable"},
        {id: 219, name: "hubbard squash", type: "vegetable"},
        {id: 220, name: "marrow  == squash ", type: "vegetable"},
        {id: 221, name: "patty pans", type: "vegetable"},
        {id: 222, name: "pumpkint", type: "vegetable"},
        {id: 223, name: "spaghetti squash", type: "vegetable"},
        {id: 224, name: "tat soi", type: "vegetable"},
        {id: 225, name: "tomato", type: "vegetable"},
        {id: 226, name: "but taxed as a ", type: "vegetable"},
        {id: 227, name: "tubers", type: "vegetable"},
        {id: 228, name: "jicama", type: "vegetable"},
        {id: 229, name: "jerusalem artichoke", type: "vegetable"},
        {id: 230, name: "potato", type: "vegetable"},
        {id: 231, name: "quandong", type: "vegetable"},
        {id: 232, name: "sunchokes", type: "vegetable"},
        {id: 233, name: "sweet potato", type: "vegetable"},
        {id: 234, name: "taro", type: "vegetable"},
        {id: 235, name: "yam", type: "vegetable"},
        {id: 236, name: "water chestnut", type: "vegetable"},
        {id: 237, name: "watercress", type: "vegetable"},
        {id: 238, name: "cucumber", type: "vegetable"},
        {id: 239, name: "beef", type: "meat"},
        {id: 240, name: "sirloin", type: "meat"},
        {id: 241, name: "steak", type: "meat"},
        {id: 242, name: "ground beef", type: "meat"},
        {id: 243, name: "meatballs", type: "meat"},
        {id: 244, name: "roast", type: "meat"},
        {id: 245, name: "salami", type: "meat"},
        {id: 246, name: "pepperoni", type: "meat"},
        {id: 247, name: "ham", type: "meat"},
        {id: 248, name: "bacon", type: "meat"},
        {id: 249, name: "eggs", type: "meat"},
        {id: 250, name: "chicken breasts", type: "meat"},
        {id: 251, name: "chicken wings", type: "meat"},
        {id: 252, name: "chicken thighs", type: "meat"},
        {id: 253, name: "sausage", type: "meat"},
        {id: 254, name: "turkey breast", type: "meat"},
        {id: 255, name: "duck breast", type: "meat"},
        {id: 256, name: "pork", type: "meat"},
        {id: 257, name: "pork chops", type: "meat"},
      ]);
    });
};
