
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('foods').del()
    .then(function () {
      // Inserts seed entries
      return knex('foods').insert([
        {id: 1, name: "Açaí", type: "fruit"},
        {id: 2, name: "Apple", type: "fruit"},
        {id: 3, name: "Akee", type: "fruit"},
        {id: 4, name: "Apricot", type: "fruit"},
        {id: 5, name: "Avocado", type: "fruit"},
        {id: 6, name: "Banana", type: "fruit"},
        {id: 7, name: "Bilberry", type: "fruit"},
        {id: 8, name: "Blackberry", type: "fruit"},
        {id: 9, name: "Blackcurrant", type: "fruit"},
        {id: 10, name: "Black", type: "fruit"},
        {id: 11, name: "sapote", type: "fruit"},
        {id: 12, name: "Blueberry", type: "fruit"},
        {id: 13, name: "Boysenberry", type: "fruit"},
        {id: 14, name: "Crab apples", type: "fruit"},
        {id: 15, name: "Currant", type: "fruit"},
        {id: 16, name: "Cherry", type: "fruit"},
        {id: 17, name: "Cherimoya", type: "fruit"},
        {id: 18, name: "Chico fruit", type: "fruit"},
        {id: 19, name: "Cloudberry", type: "fruit"},
        {id: 20, name: "Coconut", type: "fruit"},
        {id: 21, name: "Cranberry", type: "fruit"},
        {id: 22, name: "Cucumber", type: "fruit"},
        {id: 23, name: "Custard apple", type: "fruit"},
        {id: 24, name: "Damson", type: "fruit"},
        {id: 25, name: "Date", type: "fruit"},
        {id: 26, name: "Dragonfruit", type: "fruit"},
        {id: 27, name: "Durian", type: "fruit"},
        {id: 28, name: "Elderberry", type: "fruit"},
        {id: 29, name: "Feijoa", type: "fruit"},
        {id: 30, name: "Fig", type: "fruit"},
        {id: 31, name: "Goji berry", type: "fruit"},
        {id: 32, name: "Gooseberry", type: "fruit"},
        {id: 33, name: "Grape", type: "fruit"},
        {id: 34, name: "Raisin", type: "fruit"},
        {id: 35, name: "Grapefruit", type: "fruit"},
        {id: 36, name: "Guava", type: "fruit"},
        {id: 37, name: "Honeyberry", type: "fruit"},
        {id: 38, name: "Huckleberry", type: "fruit"},
        {id: 39, name: "Jabuticaba", type: "fruit"},
        {id: 40, name: "Jackfruit", type: "fruit"},
        {id: 41, name: "Jambul", type: "fruit"},
        {id: 42, name: "Japanese plum", type: "fruit"},
        {id: 43, name: "Jostaberry", type: "fruit"},
        {id: 44, name: "Jujube", type: "fruit"},
        {id: 45, name: "Juniper berry", type: "fruit"},
        {id: 46, name: "Kiwano", type: "fruit"},
        {id: 47, name: "Kiwifruit", type: "fruit"},
        {id: 48, name: "Kumquat", type: "fruit"},
        {id: 49, name: "Lemon", type: "fruit"},
        {id: 50, name: "Lime", type: "fruit"},
        {id: 51, name: "Loquat", type: "fruit"},
        {id: 52, name: "Longan", type: "fruit"},
        {id: 53, name: "Lychee", type: "fruit"},
        {id: 54, name: "Mango", type: "fruit"},
        {id: 55, name: "Mangosteen", type: "fruit"},
        {id: 56, name: "Marionberry", type: "fruit"},
        {id: 57, name: "Melon", type: "fruit"},
        {id: 58, name: "Cantaloupe", type: "fruit"},
        {id: 59, name: "Honeydew", type: "fruit"},
        {id: 60, name: "Watermelon", type: "fruit"},
        {id: 61, name: "Miraclefruit", type: "fruit"},
        {id: 62, name: "Mulberry", type: "fruit"},
        {id: 63, name: "Nectarine", type: "fruit"},
        {id: 64, name: "Nance", type: "fruit"},
        {id: 65, name: "Olive", type: "fruit"},
        {id: 66, name: "Orange", type: "fruit"},
        {id: 67, name: "Blood orange", type: "fruit"},
        {id: 68, name: "Clementine", type: "fruit"},
        {id: 69, name: "Mandarine", type: "fruit"},
        {id: 70, name: "Tangerine", type: "fruit"},
        {id: 71, name: "Papaya", type: "fruit"},
        {id: 72, name: "Passionfruit", type: "fruit"},
        {id: 73, name: "Peach", type: "fruit"},
        {id: 74, name: "Pear", type: "fruit"},
        {id: 75, name: "Persimmon", type: "fruit"},
        {id: 76, name: "Plantain", type: "fruit"},
        {id: 77, name: "Plum", type: "fruit"},
        {id: 78, name: "Prune", type: "fruit"},
        {id: 79, name: "Pineapple", type: "fruit"},
        {id: 80, name: "Pineberry", type: "fruit"},
        {id: 81, name: "Plumcot", type: "fruit"},
        {id: 82, name: "Pomegranate", type: "fruit"},
        {id: 83, name: "Pomelo", type: "fruit"},
        {id: 84, name: "Purple mangosteen", type: "fruit"},
        {id: 85, name: "Quince", type: "fruit"},
        {id: 86, name: "Raspberry", type: "fruit"},
        {id: 87, name: "Salmonberry", type: "fruit"},
        {id: 88, name: "Rambutan", type: "fruit"},
        {id: 89, name: "Redcurrant", type: "fruit"},
        {id: 90, name: "Salal berry", type: "fruit"},
        {id: 91, name: "Salak", type: "fruit"},
        {id: 92, name: "Satsuma", type: "fruit"},
        {id: 93, name: "Soursop", type: "fruit"},
        {id: 94, name: "Star apple", type: "fruit"},
        {id: 95, name: "Star fruit", type: "fruit"},
        {id: 96, name: "Strawberry", type: "fruit"},
        {id: 97, name: "Surinam cherry", type: "fruit"},
        {id: 98, name: "Tamarillo", type: "fruit"},
        {id: 99, name: "Tamarind", type: "fruit"},
        {id: 100, name: "Ugli fruit", type: "fruit"},
        {id: 101, name: "Yuzu", type: "fruit"},
        {id: 102, name: "White currant", type: "fruit"},
        {id: 103, name: "White Sapote", type: "fruit"},
        {id: 104, name: "aubergine ", type: "vegetable"},
        {id: 105, name: "amrud", type: "vegetable"},
        {id: 106, name: "asparagus", type: "vegetable"},
        {id: 107, name: "legumes", type: "vegetable"},
        {id: 108, name: "alfalfa sprouts", type: "vegetable"},
        {id: 109, name: "azuki beans ", type: "vegetable"},
        {id: 110, name: "bean sprouts", type: "vegetable"},
        {id: 111, name: "black beans", type: "vegetable"},
        {id: 112, name: "black-eyed peas", type: "vegetable"},
        {id: 113, name: "borlotti bean", type: "vegetable"},
        {id: 114, name: "broad beans", type: "vegetable"},
        {id: 115, name: "chickpeas", type: "vegetable"},
        {id: 116, name: "garbanzos", type: "vegetable"},
        {id: 117, name: "or ceci beans", type: "vegetable"},
        {id: 118, name: "green beans", type: "vegetable"},
        {id: 119, name: "kidney beans", type: "vegetable"},
        {id: 120, name: "lentils", type: "vegetable"},
        {id: 121, name: "lima beans or Butter bean", type: "vegetable"},
        {id: 122, name: "mung beans", type: "vegetable"},
        {id: 123, name: "navy beans", type: "vegetable"},
        {id: 124, name: "pinto beans", type: "vegetable"},
        {id: 125, name: "runner beans", type: "vegetable"},
        {id: 126, name: "split peas", type: "vegetable"},
        {id: 127, name: "soy beans", type: "vegetable"},
        {id: 128, name: "peas", type: "vegetable"},
        {id: 129, name: "snap peas", type: "vegetable"},
        {id: 130, name: "broccoflower ", type: "vegetable"},
        {id: 131, name: "broccoli ", type: "vegetable"},
        {id: 132, name: "brussels sprouts", type: "vegetable"},
        {id: 133, name: "cabbage", type: "vegetable"},
        {id: 134, name: "kohlrabi", type: "vegetable"},
        {id: 135, name: "cauliflower", type: "vegetable"},
        {id: 136, name: "celery", type: "vegetable"},
        {id: 137, name: "endive", type: "vegetable"},
        {id: 138, name: "fiddleheads", type: "vegetable"},
        {id: 139, name: "frisee", type: "vegetable"},
        {id: 140, name: "fennel", type: "vegetable"},
        {id: 141, name: "greens", type: "vegetable"},
        {id: 142, name: "beet greens ", type: "vegetable"},
        {id: 143, name: "bok choy", type: "vegetable"},
        {id: 144, name: "chard ", type: "vegetable"},
        {id: 145, name: "collard greens", type: "vegetable"},
        {id: 146, name: "kale", type: "vegetable"},
        {id: 147, name: "mustard greens", type: "vegetable"},
        {id: 148, name: "spinach", type: "vegetable"},
        {id: 149, name: "quinoa", type: "vegetable"},
        {id: 150, name: "anise", type: "vegetable"},
        {id: 151, name: "basil", type: "vegetable"},
        {id: 152, name: "caraway", type: "vegetable"},
        {id: 153, name: "cilantro", type: "vegetable"},
        {id: 154, name: "coriander", type: "vegetable"},
        {id: 155, name: "chamomile", type: "vegetable"},
        {id: 156, name: "dill", type: "vegetable"},
        {id: 157, name: "fennel", type: "vegetable"},
        {id: 158, name: "lavender", type: "vegetable"},
        {id: 159, name: "lemon Grass", type: "vegetable"},
        {id: 160, name: "marjoram", type: "vegetable"},
        {id: 161, name: "oregano", type: "vegetable"},
        {id: 162, name: "parsley", type: "vegetable"},
        {id: 163, name: "rosemary", type: "vegetable"},
        {id: 164, name: "sage", type: "vegetable"},
        {id: 165, name: "thyme", type: "vegetable"},
        {id: 166, name: "lettuce", type: "vegetable"},
        {id: 167, name: "arugula", type: "vegetable"},
        {id: 168, name: "mushrooms ", type: "vegetable"},
        {id: 169, name: "nettles", type: "vegetable"},
        {id: 170, name: "New Zealand spinach", type: "vegetable"},
        {id: 171, name: "okra", type: "vegetable"},
        {id: 172, name: "onions", type: "vegetable"},
        {id: 173, name: "Chives", type: "vegetable"},
        {id: 174, name: "Garlic", type: "vegetable"},
        {id: 175, name: "Leek", type: "vegetable"},
        {id: 176, name: "onion", type: "vegetable"},
        {id: 177, name: "shallot", type: "vegetable"},
        {id: 178, name: "scallion", type: "vegetable"},
        {id: 179, name: "", type: "vegetable"},
        {id: 180, name: "green onion ", type: "vegetable"},
        {id: 181, name: "parsley", type: "vegetable"},
        {id: 182, name: "peppers ", type: "vegetable"},
        {id: 183, name: "bell pepper", type: "vegetable"},
        {id: 184, name: "chili pepper", type: "vegetable"},
        {id: 185, name: "Jalapeño", type: "vegetable"},
        {id: 186, name: "Habanero", type: "vegetable"},
        {id: 187, name: "Paprika", type: "vegetable"},
        {id: 188, name: "Tabasco pepper", type: "vegetable"},
        {id: 189, name: "Cayenne pepper", type: "vegetable"},
        {id: 190, name: "radicchio", type: "vegetable"},
        {id: 191, name: "rhubarb", type: "vegetable"},
        {id: 192, name: "root vegetables", type: "vegetable"},
        {id: 193, name: "beetroot ", type: "vegetable"},
        {id: 194, name: "mangel-wurzel", type: "vegetable"},
        {id: 195, name: "carrot", type: "vegetable"},
        {id: 196, name: "celeriac", type: "vegetable"},
        {id: 197, name: "daikon", type: "vegetable"},
        {id: 198, name: "ginger", type: "vegetable"},
        {id: 199, name: "parsnip", type: "vegetable"},
        {id: 200, name: "rutabaga", type: "vegetable"},
        {id: 201, name: "turnip", type: "vegetable"},
        {id: 202, name: "radish", type: "vegetable"},
        {id: 203, name: "wasabi", type: "vegetable"},
        {id: 204, name: "horseradish", type: "vegetable"},
        {id: 205, name: "white radish", type: "vegetable"},
        {id: 206, name: "salsify ", type: "vegetable"},
        {id: 207, name: "skirret", type: "vegetable"},
        {id: 208, name: "sweetcorn ", type: "vegetable"},
        {id: 209, name: "topinambur", type: "vegetable"},
        {id: 210, name: "squashes ", type: "vegetable"},
        {id: 211, name: "acorn squash", type: "vegetable"},
        {id: 212, name: "bitter melon", type: "vegetable"},
        {id: 213, name: "butternut squash", type: "vegetable"},
        {id: 214, name: "banana squash", type: "vegetable"},
        {id: 215, name: "Zucchini ", type: "vegetable"},
        {id: 216, name: "cucumber ", type: "vegetable"},
        {id: 217, name: "delicata", type: "vegetable"},
        {id: 218, name: "gem squash", type: "vegetable"},
        {id: 219, name: "hubbard squash", type: "vegetable"},
        {id: 220, name: "marrow  == Squash ", type: "vegetable"},
        {id: 221, name: "patty pans", type: "vegetable"},
        {id: 222, name: "pumpkint", type: "vegetable"},
        {id: 223, name: "spaghetti squash", type: "vegetable"},
        {id: 224, name: "tat soi", type: "vegetable"},
        {id: 225, name: "tomato", type: "vegetable"},
        {id: 226, name: "but taxed as a ", type: "vegetable"},
        {id: 227, name: "tubers", type: "vegetable"},
        {id: 228, name: "jicama", type: "vegetable"},
        {id: 229, name: "jerusalem artichoke", type: "vegetable"},
        {id: 230, name: "potato", type: "vegetable"},
        {id: 231, name: "quandong", type: "vegetable"},
        {id: 232, name: "sunchokes", type: "vegetable"},
        {id: 233, name: "sweet potato", type: "vegetable"},
        {id: 234, name: "taro", type: "vegetable"},
        {id: 235, name: "yam", type: "vegetable"},
        {id: 236, name: "water chestnut", type: "vegetable"},
        {id: 237, name: "watercress", type: "vegetable"},
        {id: 238, name: "Cucumber", type: "vegetable"},
        {id: 239, name: "beef", type: "meat"},
        {id: 240, name: "sirloin", type: "meat"},
        {id: 241, name: "steak", type: "meat"},
        {id: 242, name: "ground beef", type: "meat"},
        {id: 243, name: "meatballs", type: "meat"},
        {id: 244, name: "roast", type: "meat"},
        {id: 245, name: "salami", type: "meat"},
        {id: 246, name: "pepperoni", type: "meat"},
        {id: 247, name: "ham", type: "meat"},
        {id: 248, name: "bacon", type: "meat"},
        {id: 249, name: "eggs", type: "meat"},
        {id: 250, name: "chicken breasts", type: "meat"},
        {id: 251, name: "chicken wings", type: "meat"},
        {id: 252, name: "chicken thighs", type: "meat"},
        {id: 253, name: "sausage", type: "meat"},
        {id: 254, name: "turkey breast", type: "meat"},
        {id: 255, name: "duck breast", type: "meat"},
        {id: 256, name: "pork", type: "meat"},
        {id: 257, name: "pork chops", type: "meat"},
        {id: 258, name: "artichoke", type: "vegetable"},

      ]);
    });
};
